"""Seed data for Indian states + Union Territories with alias lists.

Aliases drive state-tagging: when an Article's entities or content mention
any alias, the parent Story gets tagged with that state. Keep aliases
high-signal — avoid generic words (no "city", "district").
"""

INDIAN_STATES: list[dict] = [
    # ---------- 28 States ----------
    {"name": "Andhra Pradesh", "code": "AP",
     "aliases": ["Visakhapatnam", "Vijayawada", "Tirupati", "Guntur", "Amaravati"]},
    {"name": "Arunachal Pradesh", "code": "AR",
     "aliases": ["Itanagar", "Tawang", "Naharlagun"]},
    {"name": "Assam", "code": "AS",
     "aliases": ["Guwahati", "Dispur", "Dibrugarh", "Silchar", "Jorhat"]},
    {"name": "Bihar", "code": "BR",
     "aliases": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"]},
    {"name": "Chhattisgarh", "code": "CG",
     "aliases": ["Raipur", "Bhilai", "Bilaspur", "Korba"]},
    {"name": "Goa", "code": "GA",
     "aliases": ["Panaji", "Vasco da Gama", "Margao"]},
    {"name": "Gujarat", "code": "GJ",
     "aliases": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar", "Jamnagar"]},
    {"name": "Haryana", "code": "HR",
     "aliases": ["Gurugram", "Gurgaon", "Faridabad", "Panipat", "Karnal", "Chandigarh"]},
    {"name": "Himachal Pradesh", "code": "HP",
     "aliases": ["Shimla", "Manali", "Dharamshala", "Kullu"]},
    {"name": "Jharkhand", "code": "JH",
     "aliases": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"]},
    {"name": "Karnataka", "code": "KA",
     "aliases": ["Bengaluru", "Bangalore", "Mysore", "Mysuru", "Mangalore", "Mangaluru", "Hubli", "Belgaum"]},
    {"name": "Kerala", "code": "KL",
     "aliases": ["Thiruvananthapuram", "Trivandrum", "Kochi", "Cochin", "Kozhikode", "Calicut", "Thrissur"]},
    {"name": "Madhya Pradesh", "code": "MP",
     "aliases": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain"]},
    {"name": "Maharashtra", "code": "MH",
     "aliases": ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane", "Bombay"]},
    {"name": "Manipur", "code": "MN",
     "aliases": ["Imphal", "Bishnupur", "Churachandpur"]},
    {"name": "Meghalaya", "code": "ML",
     "aliases": ["Shillong", "Tura"]},
    {"name": "Mizoram", "code": "MZ",
     "aliases": ["Aizawl", "Lunglei"]},
    {"name": "Nagaland", "code": "NL",
     "aliases": ["Kohima", "Dimapur"]},
    {"name": "Odisha", "code": "OR",
     "aliases": ["Bhubaneswar", "Cuttack", "Rourkela", "Puri"]},
    {"name": "Punjab", "code": "PB",
     "aliases": ["Amritsar", "Ludhiana", "Jalandhar", "Patiala", "Mohali"]},
    {"name": "Rajasthan", "code": "RJ",
     "aliases": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer"]},
    {"name": "Sikkim", "code": "SK",
     "aliases": ["Gangtok"]},
    {"name": "Tamil Nadu", "code": "TN",
     "aliases": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Trichy", "Salem", "Madras"]},
    {"name": "Telangana", "code": "TS",
     "aliases": ["Hyderabad", "Warangal", "Karimnagar", "Nizamabad"]},
    {"name": "Tripura", "code": "TR",
     "aliases": ["Agartala"]},
    {"name": "Uttar Pradesh", "code": "UP",
     "aliases": ["Lucknow", "Noida", "Ghaziabad", "Kanpur", "Varanasi", "Prayagraj", "Allahabad", "Agra", "Meerut", "Ayodhya"]},
    {"name": "Uttarakhand", "code": "UK",
     "aliases": ["Dehradun", "Haridwar", "Rishikesh", "Nainital"]},
    {"name": "West Bengal", "code": "WB",
     "aliases": ["Kolkata", "Howrah", "Siliguri", "Durgapur", "Asansol", "Calcutta"]},

    # ---------- 8 Union Territories ----------
    {"name": "Andaman and Nicobar Islands", "code": "AN",
     "aliases": ["Port Blair"]},
    {"name": "Chandigarh", "code": "CH",
     "aliases": []},
    {"name": "Dadra and Nagar Haveli and Daman and Diu", "code": "DH",
     "aliases": ["Daman", "Diu", "Silvassa"]},
    {"name": "Delhi", "code": "DL",
     "aliases": ["New Delhi", "NCR", "National Capital Region"]},
    {"name": "Jammu and Kashmir", "code": "JK",
     "aliases": ["Srinagar", "Jammu", "Kashmir", "Anantnag", "Baramulla"]},
    {"name": "Ladakh", "code": "LA",
     "aliases": ["Leh", "Kargil"]},
    {"name": "Lakshadweep", "code": "LD",
     "aliases": ["Kavaratti"]},
    {"name": "Puducherry", "code": "PY",
     "aliases": ["Pondicherry"]},
]
