"""Curated source seed: 70 India + 50 global English-language RSS feeds.

Schema for each row:
    slug             — unique stable id (kebab-case)
    name             — display name
    url              — homepage
    rss_url          — feed URL
    country          — ISO-3166 alpha-2
    region           — state/region for sub-national sources, else None
    region_bucket    — "national" or "regional"
    political_lean   — "left" | "centrist" | "right" | "unknown"
    tier             — "A" (top), "B" (strong), "C" (long tail)

Some RSS URLs are best-effort; the ingestion pipeline marks repeated failures
and deactivates them. Edit this file to add/remove sources.
"""

SOURCES: list[dict] = [
    # ---------- INDIA: National English dailies (10) ----------
    {"slug": "times-of-india", "name": "Times of India", "url": "https://timesofindia.indiatimes.com",
     "rss_url": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "the-hindu", "name": "The Hindu", "url": "https://www.thehindu.com",
     "rss_url": "https://www.thehindu.com/news/national/feeder/default.rss",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "indian-express", "name": "Indian Express", "url": "https://indianexpress.com",
     "rss_url": "https://indianexpress.com/section/india/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "hindustan-times", "name": "Hindustan Times", "url": "https://www.hindustantimes.com",
     "rss_url": "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "telegraph-india", "name": "Telegraph India", "url": "https://www.telegraphindia.com",
     "rss_url": "https://www.telegraphindia.com/feeds/rss.jsp",
     "country": "IN", "region": "West Bengal", "region_bucket": "national",
     "political_lean": "left", "tier": "B"},
    {"slug": "deccan-herald", "name": "Deccan Herald", "url": "https://www.deccanherald.com",
     "rss_url": "https://www.deccanherald.com/rss-feed",
     "country": "IN", "region": "Karnataka", "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "the-tribune", "name": "The Tribune (India)", "url": "https://www.tribuneindia.com",
     "rss_url": "https://www.tribuneindia.com/rss/feed?catId=20",
     "country": "IN", "region": "Punjab", "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "the-statesman", "name": "The Statesman", "url": "https://www.thestatesman.com",
     "rss_url": "https://www.thestatesman.com/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "dna-india", "name": "DNA India", "url": "https://www.dnaindia.com",
     "rss_url": "https://www.dnaindia.com/feeds/india.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "free-press-journal", "name": "Free Press Journal", "url": "https://www.freepressjournal.in",
     "rss_url": "https://www.freepressjournal.in/stories.rss",
     "country": "IN", "region": "Maharashtra", "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},

    # ---------- INDIA: Business (8) ----------
    {"slug": "economic-times", "name": "Economic Times", "url": "https://economictimes.indiatimes.com",
     "rss_url": "https://economictimes.indiatimes.com/rssfeedstopstories.cms",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "mint", "name": "Mint (LiveMint)", "url": "https://www.livemint.com",
     "rss_url": "https://www.livemint.com/rss/news",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "business-standard", "name": "Business Standard", "url": "https://www.business-standard.com",
     "rss_url": "https://www.business-standard.com/rss/home_page_top_stories.rss",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "financial-express", "name": "Financial Express", "url": "https://www.financialexpress.com",
     "rss_url": "https://www.financialexpress.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "moneycontrol", "name": "Moneycontrol", "url": "https://www.moneycontrol.com",
     "rss_url": "https://www.moneycontrol.com/rss/latestnews.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "bq-prime", "name": "NDTV Profit (ex-BQ Prime)", "url": "https://www.ndtvprofit.com",
     "rss_url": "https://www.ndtvprofit.com/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C", "is_active": False},
    {"slug": "inc42", "name": "Inc42", "url": "https://inc42.com",
     "rss_url": "https://inc42.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "C"},
    {"slug": "entrackr", "name": "Entrackr", "url": "https://entrackr.com",
     "rss_url": "https://entrackr.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "C"},

    # ---------- INDIA: Broadcast / digital news (10) ----------
    {"slug": "ndtv", "name": "NDTV", "url": "https://www.ndtv.com",
     "rss_url": "https://feeds.feedburner.com/ndtvnews-top-stories",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "india-today", "name": "India Today", "url": "https://www.indiatoday.in",
     "rss_url": "https://www.indiatoday.in/rss/home",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "news18", "name": "News18", "url": "https://www.news18.com",
     "rss_url": "https://www.news18.com/commonfeeds/v1/eng/rss/india.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},
    {"slug": "republic-world", "name": "Republic World", "url": "https://www.republicworld.com",
     "rss_url": "https://www.republicworld.com/rss/section/india-news.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},
    {"slug": "times-now", "name": "Times Now", "url": "https://www.timesnownews.com",
     "rss_url": "https://www.timesnownews.com/rssfeeds/-2128936835.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},
    {"slug": "wion", "name": "WION", "url": "https://www.wionews.com",
     "rss_url": "https://www.wionews.com/rss/world.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "firstpost", "name": "Firstpost", "url": "https://www.firstpost.com",
     "rss_url": "https://www.firstpost.com/rss/india.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "outlook-india", "name": "Outlook India", "url": "https://www.outlookindia.com",
     "rss_url": "https://www.outlookindia.com/rss/main/magazine",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "the-quint", "name": "The Quint", "url": "https://www.thequint.com",
     "rss_url": "https://www.thequint.com/stories.rss",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "B"},
    {"slug": "abp-live", "name": "ABP Live (English)", "url": "https://news.abplive.com",
     "rss_url": "https://news.abplive.com/feeds/feed.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},

    # ---------- INDIA: Digital-native longform (7) ----------
    {"slug": "the-wire", "name": "The Wire", "url": "https://thewire.in",
     "rss_url": "https://thewire.in/rss",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "scroll-in", "name": "Scroll.in", "url": "https://scroll.in",
     "rss_url": "https://scroll.in/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "the-print", "name": "The Print", "url": "https://theprint.in",
     "rss_url": "https://theprint.in/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "newslaundry", "name": "Newslaundry", "url": "https://www.newslaundry.com",
     "rss_url": "https://www.newslaundry.com/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "B"},
    {"slug": "the-caravan", "name": "The Caravan", "url": "https://caravanmagazine.in",
     "rss_url": "https://caravanmagazine.in/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "B"},
    {"slug": "yourstory", "name": "YourStory", "url": "https://yourstory.com",
     "rss_url": "https://yourstory.com/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "C"},
    {"slug": "downtoearth", "name": "Down To Earth", "url": "https://www.downtoearth.org.in",
     "rss_url": "https://www.downtoearth.org.in/rss/india",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "C"},

    # ---------- INDIA: Regional English (15) ----------
    {"slug": "new-indian-express", "name": "New Indian Express", "url": "https://www.newindianexpress.com",
     "rss_url": "https://www.newindianexpress.com/Nation/rssfeed/?id=170&getXmlFeed=true",
     "country": "IN", "region": "Tamil Nadu", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "deccan-chronicle", "name": "Deccan Chronicle", "url": "https://www.deccanchronicle.com",
     "rss_url": "https://www.deccanchronicle.com/rss_feed/",
     "country": "IN", "region": "Telangana", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "mid-day", "name": "Mid-Day Mumbai", "url": "https://www.mid-day.com",
     "rss_url": "https://www.mid-day.com/rss/news",
     "country": "IN", "region": "Maharashtra", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "kashmir-reader", "name": "Kashmir Reader", "url": "https://kashmirreader.com",
     "rss_url": "https://kashmirreader.com/feed/",
     "country": "IN", "region": "Jammu and Kashmir", "region_bucket": "regional",
     "political_lean": "unknown", "tier": "C"},
    {"slug": "greater-kashmir", "name": "Greater Kashmir", "url": "https://www.greaterkashmir.com",
     "rss_url": "https://www.greaterkashmir.com/feed",
     "country": "IN", "region": "Jammu and Kashmir", "region_bucket": "regional",
     "political_lean": "unknown", "tier": "C"},
    {"slug": "northeast-now", "name": "Northeast Now", "url": "https://nenow.in",
     "rss_url": "https://nenow.in/feed",
     "country": "IN", "region": "Assam", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "telangana-today", "name": "Telangana Today", "url": "https://telanganatoday.com",
     "rss_url": "https://telanganatoday.com/feed",
     "country": "IN", "region": "Telangana", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "sentinel-assam", "name": "Sentinel Assam", "url": "https://www.sentinelassam.com",
     "rss_url": "https://www.sentinelassam.com/feeds/",
     "country": "IN", "region": "Assam", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "shillong-times", "name": "The Shillong Times", "url": "https://theshillongtimes.com",
     "rss_url": "https://theshillongtimes.com/feed/",
     "country": "IN", "region": "Meghalaya", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "eastmojo", "name": "EastMojo", "url": "https://www.eastmojo.com",
     "rss_url": "https://www.eastmojo.com/feed/",
     "country": "IN", "region": "Assam", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "bangalore-mirror", "name": "Bangalore Mirror", "url": "https://bangaloremirror.indiatimes.com",
     "rss_url": "https://bangaloremirror.indiatimes.com/rssfeedstopstories.cms",
     "country": "IN", "region": "Karnataka", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "onmanorama", "name": "Onmanorama", "url": "https://www.onmanorama.com",
     "rss_url": "https://www.onmanorama.com/news.feeds.onmanorama-topstories.rss",
     "country": "IN", "region": "Kerala", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "kashmir-observer", "name": "Kashmir Observer", "url": "https://kashmirobserver.net",
     "rss_url": "https://kashmirobserver.net/feed/",
     "country": "IN", "region": "Jammu and Kashmir", "region_bucket": "regional",
     "political_lean": "unknown", "tier": "C"},
    {"slug": "nagaland-post", "name": "Nagaland Post", "url": "https://www.nagalandpost.com",
     "rss_url": "https://www.nagalandpost.com/index.php/rss/all",
     "country": "IN", "region": "Nagaland", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "the-goan", "name": "The Goan", "url": "https://www.thegoan.net",
     "rss_url": "https://www.thegoan.net/rss/all",
     "country": "IN", "region": "Goa", "region_bucket": "regional",
     "political_lean": "centrist", "tier": "C"},

    # ---------- INDIA: Sports / Tech (5) ----------
    {"slug": "cricbuzz", "name": "Cricbuzz", "url": "https://www.cricbuzz.com",
     "rss_url": "https://www.cricbuzz.com/cricket-news-rss/news.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "B"},
    {"slug": "espncricinfo", "name": "ESPN Cricinfo", "url": "https://www.espncricinfo.com",
     "rss_url": "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "B"},
    {"slug": "sportstar", "name": "Sportstar", "url": "https://sportstar.thehindu.com",
     "rss_url": "https://sportstar.thehindu.com/feeder/default.rss",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "gadgets360", "name": "Gadgets360", "url": "https://gadgets360.com",
     "rss_url": "https://gadgets360.com/rss/news",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "C"},
    {"slug": "tech-in-asia", "name": "Tech in Asia", "url": "https://www.techinasia.com",
     "rss_url": "https://www.techinasia.com/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "C"},

    # ---------- INDIA: Right-of-center digital (7) ----------
    {"slug": "opindia", "name": "OpIndia", "url": "https://www.opindia.com",
     "rss_url": "https://www.opindia.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},
    {"slug": "swarajya", "name": "Swarajya", "url": "https://swarajyamag.com",
     "rss_url": "https://swarajyamag.com/feed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},
    {"slug": "tfipost", "name": "TFIPost", "url": "https://tfipost.com",
     "rss_url": "https://tfipost.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "C"},
    {"slug": "organiser", "name": "Organiser", "url": "https://organiser.org",
     "rss_url": "https://organiser.org/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "C"},
    {"slug": "sirf-news", "name": "Sirf News", "url": "https://www.sirfnews.com",
     "rss_url": "https://www.sirfnews.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "C"},
    {"slug": "dailyo", "name": "DailyO", "url": "https://www.dailyo.in",
     "rss_url": "https://www.dailyo.in/news/rss",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "mynation", "name": "MyNation", "url": "https://www.mynation.com",
     "rss_url": "https://www.mynation.com/rss/india",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "C"},

    # ---------- INDIA: Defence / strategic (2) ----------
    {"slug": "orf", "name": "Observer Research Foundation", "url": "https://www.orfonline.org",
     "rss_url": "https://www.orfonline.org/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "bharat-shakti", "name": "Bharat Shakti", "url": "https://bharatshakti.in",
     "rss_url": "https://bharatshakti.in/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},

    # ---------- INDIA: Opinion / longform (2) ----------
    {"slug": "frontline", "name": "Frontline (Hindu)", "url": "https://frontline.thehindu.com",
     "rss_url": "https://frontline.thehindu.com/feeder/default.rss",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "C"},
    {"slug": "open-magazine", "name": "Open Magazine", "url": "https://www.openthemagazine.com",
     "rss_url": "https://www.openthemagazine.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},

    # ---------- INDIA: Tech/policy + south India + policy (4) ----------
    {"slug": "medianama", "name": "MediaNama", "url": "https://www.medianama.com",
     "rss_url": "https://www.medianama.com/feed/",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "the-news-minute", "name": "The News Minute", "url": "https://www.thenewsminute.com",
     "rss_url": "https://www.thenewsminute.com/feed",
     "country": "IN", "region": "Tamil Nadu", "region_bucket": "national",
     "political_lean": "left", "tier": "B"},
    {"slug": "the-citizen", "name": "The Citizen", "url": "https://www.thecitizen.in",
     "rss_url": "https://www.thecitizen.in/index.php/en/rssfeed",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "C"},
    {"slug": "india-forum", "name": "The India Forum", "url": "https://www.theindiaforum.in",
     "rss_url": "https://www.theindiaforum.in/rss.xml",
     "country": "IN", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "C"},

    # ============================================================
    # GLOBAL (50)
    # ============================================================

    # ---------- US national (12) ----------
    {"slug": "nytimes", "name": "New York Times", "url": "https://www.nytimes.com",
     "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "washington-post", "name": "Washington Post", "url": "https://www.washingtonpost.com",
     "rss_url": "https://feeds.washingtonpost.com/rss/world",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "wsj", "name": "Wall Street Journal", "url": "https://www.wsj.com",
     "rss_url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "A"},
    {"slug": "npr", "name": "NPR", "url": "https://www.npr.org",
     "rss_url": "https://feeds.npr.org/1001/rss.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "ap-news", "name": "Associated Press", "url": "https://apnews.com",
     "rss_url": "https://apnews.com/index.rss",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A", "is_active": False},  # AP killed public RSS
    {"slug": "abc-news", "name": "ABC News", "url": "https://abcnews.go.com",
     "rss_url": "https://abcnews.go.com/abcnews/topstories",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "cbs-news", "name": "CBS News", "url": "https://www.cbsnews.com",
     "rss_url": "https://www.cbsnews.com/latest/rss/main",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "nbc-news", "name": "NBC News", "url": "https://www.nbcnews.com",
     "rss_url": "https://feeds.nbcnews.com/nbcnews/public/news",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "cnn", "name": "CNN", "url": "https://www.cnn.com",
     "rss_url": "http://rss.cnn.com/rss/cnn_topstories.rss",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "politico", "name": "Politico", "url": "https://www.politico.com",
     "rss_url": "https://rss.politico.com/politics-news.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "axios", "name": "Axios", "url": "https://www.axios.com",
     "rss_url": "https://api.axios.com/feed/",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "the-atlantic", "name": "The Atlantic", "url": "https://www.theatlantic.com",
     "rss_url": "https://www.theatlantic.com/feed/all/",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "B"},

    # ---------- UK (8) ----------
    {"slug": "bbc-news", "name": "BBC News", "url": "https://www.bbc.com/news",
     "rss_url": "http://feeds.bbci.co.uk/news/rss.xml",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "guardian", "name": "The Guardian", "url": "https://www.theguardian.com",
     "rss_url": "https://www.theguardian.com/world/rss",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "telegraph-uk", "name": "Telegraph (UK)", "url": "https://www.telegraph.co.uk",
     "rss_url": "https://www.telegraph.co.uk/news/rss.xml",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},
    {"slug": "the-times-uk", "name": "The Times (UK)", "url": "https://www.thetimes.co.uk",
     "rss_url": "https://www.thetimes.co.uk/?service=rss",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},
    {"slug": "independent", "name": "Independent", "url": "https://www.independent.co.uk",
     "rss_url": "https://www.independent.co.uk/news/uk/rss",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "B"},
    {"slug": "sky-news", "name": "Sky News", "url": "https://news.sky.com",
     "rss_url": "https://feeds.skynews.com/feeds/rss/home.xml",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "financial-times", "name": "Financial Times", "url": "https://www.ft.com",
     "rss_url": "https://www.ft.com/rss/home",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "the-economist", "name": "The Economist", "url": "https://www.economist.com",
     "rss_url": "https://www.economist.com/the-world-this-week/rss.xml",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},

    # ---------- Wire / agencies (3) ----------
    {"slug": "reuters-world", "name": "Reuters World", "url": "https://www.reuters.com",
     "rss_url": "https://www.reutersagency.com/feed/?best-topics=top-news&post_type=best",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A", "is_active": False},  # Reuters killed RSS 2023
    {"slug": "bloomberg", "name": "Bloomberg", "url": "https://www.bloomberg.com",
     "rss_url": "https://feeds.bloomberg.com/markets/news.rss",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "vox", "name": "Vox", "url": "https://www.vox.com",
     "rss_url": "https://www.vox.com/rss/index.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "B"},

    # ---------- Europe (5) ----------
    {"slug": "dw-en", "name": "Deutsche Welle (English)", "url": "https://www.dw.com/en",
     "rss_url": "https://rss.dw.com/rdf/rss-en-all",
     "country": "DE", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "euronews", "name": "Euronews", "url": "https://www.euronews.com",
     "rss_url": "https://www.euronews.com/rss?level=theme&name=news",
     "country": "FR", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "france-24", "name": "France 24", "url": "https://www.france24.com/en",
     "rss_url": "https://www.france24.com/en/rss",
     "country": "FR", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "le-monde-en", "name": "Le Monde (English)", "url": "https://www.lemonde.fr/en",
     "rss_url": "https://www.lemonde.fr/en/rss/une.xml",
     "country": "FR", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "C"},
    {"slug": "el-pais-en", "name": "El País (English)", "url": "https://english.elpais.com",
     "rss_url": "https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada",
     "country": "ES", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "C"},

    # ---------- Middle East (4) ----------
    {"slug": "al-jazeera", "name": "Al Jazeera English", "url": "https://www.aljazeera.com",
     "rss_url": "https://www.aljazeera.com/xml/rss/all.xml",
     "country": "QA", "region": None, "region_bucket": "national",
     "political_lean": "left", "tier": "A"},
    {"slug": "arab-news", "name": "Arab News", "url": "https://www.arabnews.com",
     "rss_url": "https://www.arabnews.com/rss.xml",
     "country": "SA", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "times-of-israel", "name": "Times of Israel", "url": "https://www.timesofisrael.com",
     "rss_url": "https://www.timesofisrael.com/feed/",
     "country": "IL", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "jerusalem-post", "name": "Jerusalem Post", "url": "https://www.jpost.com",
     "rss_url": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
     "country": "IL", "region": None, "region_bucket": "national",
     "political_lean": "right", "tier": "B"},

    # ---------- Asia-Pacific (6) ----------
    {"slug": "scmp", "name": "South China Morning Post", "url": "https://www.scmp.com",
     "rss_url": "https://www.scmp.com/rss/91/feed",
     "country": "HK", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "A"},
    {"slug": "japan-times", "name": "Japan Times", "url": "https://www.japantimes.co.jp",
     "rss_url": "https://www.japantimes.co.jp/feed/",
     "country": "JP", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "straits-times", "name": "The Straits Times", "url": "https://www.straitstimes.com",
     "rss_url": "https://www.straitstimes.com/news/world/rss.xml",
     "country": "SG", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "abc-australia", "name": "ABC Australia", "url": "https://www.abc.net.au/news",
     "rss_url": "https://www.abc.net.au/news/feed/45910/rss.xml",
     "country": "AU", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "sydney-morning-herald", "name": "Sydney Morning Herald", "url": "https://www.smh.com.au",
     "rss_url": "https://www.smh.com.au/rss/feed.xml",
     "country": "AU", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "channel-news-asia", "name": "Channel News Asia", "url": "https://www.channelnewsasia.com",
     "rss_url": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
     "country": "SG", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},

    # ---------- Africa / LatAm (3) ----------
    {"slug": "news24-sa", "name": "News24 (South Africa)", "url": "https://www.news24.com",
     "rss_url": "https://feeds.24.com/articles/news24/topstories/rss",
     "country": "ZA", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B"},
    {"slug": "allafrica", "name": "AllAfrica", "url": "https://allafrica.com",
     "rss_url": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
     "country": "ZA", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},
    {"slug": "buenos-aires-times", "name": "Buenos Aires Times", "url": "https://www.batimes.com.ar",
     "rss_url": "https://www.batimes.com.ar/feed",
     "country": "AR", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "C"},

    # ---------- Tech / science global (9) ----------
    {"slug": "techcrunch", "name": "TechCrunch", "url": "https://techcrunch.com",
     "rss_url": "https://techcrunch.com/feed/",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "A"},
    {"slug": "the-verge", "name": "The Verge", "url": "https://www.theverge.com",
     "rss_url": "https://www.theverge.com/rss/index.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "A"},
    {"slug": "ars-technica", "name": "Ars Technica", "url": "https://arstechnica.com",
     "rss_url": "https://feeds.arstechnica.com/arstechnica/index",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "A"},
    {"slug": "wired", "name": "Wired", "url": "https://www.wired.com",
     "rss_url": "https://www.wired.com/feed/rss",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "A"},
    {"slug": "mit-tech-review", "name": "MIT Technology Review", "url": "https://www.technologyreview.com",
     "rss_url": "https://www.technologyreview.com/feed/",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "B"},
    {"slug": "reuters-tech", "name": "Reuters Tech", "url": "https://www.reuters.com/technology/",
     "rss_url": "https://www.reutersagency.com/feed/?best-topics=tech&post_type=best",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "centrist", "tier": "B", "is_active": False},  # Reuters killed RSS 2023
    {"slug": "nature-news", "name": "Nature News", "url": "https://www.nature.com",
     "rss_url": "https://www.nature.com/nature.rss",
     "country": "GB", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "B"},
    {"slug": "science-daily", "name": "Science Daily", "url": "https://www.sciencedaily.com",
     "rss_url": "https://www.sciencedaily.com/rss/all.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "B"},
    {"slug": "engadget", "name": "Engadget", "url": "https://www.engadget.com",
     "rss_url": "https://www.engadget.com/rss.xml",
     "country": "US", "region": None, "region_bucket": "national",
     "political_lean": "unknown", "tier": "C"},
]
