"""initial schema

Revision ID: 4aabd63caf0e
Revises: 
Create Date: 2026-05-18 10:33:05.980740

"""

from collections.abc import Sequence

import sqlalchemy as sa

import pgvector.sqlalchemy

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4aabd63caf0e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Enable pgvector before any tables with Vector columns are created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=2000), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('story_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_brief_date'), 'audio_brief', ['date'], unique=True)
    op.create_table('daily_snapshot',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('top_stories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('anomalies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regional_pulse', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=True),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_name'), 'entity', ['name'], unique=False)
    op.create_index(op.f('ix_entity_slug'), 'entity', ['slug'], unique=True)
    op.create_index(op.f('ix_entity_type'), 'entity', ['type'], unique=False)
    op.create_table('indian_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('podcast_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('rss_url', sa.String(length=500), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_etag', sa.String(length=500), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_source_country'), 'podcast_source', ['country'], unique=False)
    op.create_index(op.f('ix_podcast_source_is_active'), 'podcast_source', ['is_active'], unique=False)
    op.create_index(op.f('ix_podcast_source_slug'), 'podcast_source', ['slug'], unique=True)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('rss_url', sa.String(length=500), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('political_lean', sa.String(length=20), nullable=False),
    sa.Column('region_bucket', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_etag', sa.String(length=500), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_country'), 'source', ['country'], unique=False)
    op.create_index(op.f('ix_source_is_active'), 'source', ['is_active'], unique=False)
    op.create_index(op.f('ix_source_region'), 'source', ['region'], unique=False)
    op.create_index(op.f('ix_source_slug'), 'source', ['slug'], unique=True)
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('story_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('velocity_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_slug'), 'thread', ['slug'], unique=True)
    op.create_index('ix_thread_status_last_updated', 'thread', ['status', 'last_updated_at'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_slug'), 'topic', ['slug'], unique=True)
    op.create_table('entity_cooccurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_a_id', sa.Integer(), nullable=False),
    sa.Column('entity_b_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.CheckConstraint('entity_a_id < entity_b_id', name='ck_entity_cooccurrence_order'),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_a_id', 'entity_b_id', 'window_start', name='uq_entity_cooccurrence_pair_window')
    )
    op.create_index('ix_entity_cooccurrence_window_start', 'entity_cooccurrence', ['window_start'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('articles_seen', sa.Integer(), nullable=False),
    sa.Column('articles_inserted', sa.Integer(), nullable=False),
    sa.Column('articles_skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_run_source_id'), 'ingestion_run', ['source_id'], unique=False)
    op.create_index('ix_ingestion_run_source_started', 'ingestion_run', ['source_id', 'started_at'], unique=False)
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('tldr', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('centroid_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.Column('velocity_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_state', sa.String(length=100), nullable=True),
    sa.Column('primary_country', sa.String(length=2), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('first_reported_by_source_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_reported_by_source_id'], ['source.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_first_seen_at', 'story', ['first_seen_at'], unique=False)
    op.create_index('ix_story_last_updated_at', 'story', ['last_updated_at'], unique=False)
    op.create_index('ix_story_primary_country_state', 'story', ['primary_country', 'primary_state'], unique=False)
    op.create_index(op.f('ix_story_slug'), 'story', ['slug'], unique=True)
    op.create_index(op.f('ix_story_thread_id'), 'story', ['thread_id'], unique=False)
    op.create_index('ix_story_velocity_score', 'story', ['velocity_score'], unique=False)
    op.create_table('anomaly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=True),
    sa.Column('target_story_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_detected_at', 'anomaly', ['detected_at'], unique=False)
    op.create_index('ix_anomaly_type_severity', 'anomaly', ['type', 'severity'], unique=False)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('title_hash', sa.String(length=64), nullable=False),
    sa.Column('lead', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_article_published_at', 'article', ['published_at'], unique=False)
    op.create_index(op.f('ix_article_source_id'), 'article', ['source_id'], unique=False)
    op.create_index('ix_article_story_id', 'article', ['story_id'], unique=False)
    op.create_index('ix_article_title_hash_published_at', 'article', ['title_hash', 'published_at'], unique=False)
    op.create_index(op.f('ix_article_url_hash'), 'article', ['url_hash'], unique=True)
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('audio_url', sa.String(length=2000), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['podcast_source_id'], ['podcast_source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('podcast_source_id', 'audio_url', name='uq_episode_source_audio')
    )
    op.create_index(op.f('ix_episode_podcast_source_id'), 'episode', ['podcast_source_id'], unique=False)
    op.create_index('ix_episode_published_at', 'episode', ['published_at'], unique=False)
    op.create_index(op.f('ix_episode_story_id'), 'episode', ['story_id'], unique=False)
    op.create_index(op.f('ix_episode_thread_id'), 'episode', ['thread_id'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('predicted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('predicted_outlets_24h', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome_outlets_24h', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_confidence', 'prediction', ['confidence'], unique=False)
    op.create_index('ix_prediction_predicted_at', 'prediction', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_prediction_story_id'), 'prediction', ['story_id'], unique=False)
    op.create_table('thread_story',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('story_added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'story_id')
    )
    op.create_index('ix_thread_story_thread_added', 'thread_story', ['thread_id', 'story_added_at'], unique=False)
    op.create_table('article_entity',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'entity_id')
    )
    op.create_table('article_topic',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'topic_id')
    )
    # ### end Alembic commands ###

    # HNSW indexes for cosine-similarity kNN on vector columns.
    # m=16, ef_construction=64 are good defaults for ~1M vectors at 384 dim.
    op.execute(
        "CREATE INDEX ix_article_embedding_hnsw ON article "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_story_centroid_embedding_hnsw ON story "
        "USING hnsw (centroid_embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_episode_embedding_hnsw ON episode "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    # Drop HNSW indexes before the tables that contain them.
    op.execute("DROP INDEX IF EXISTS ix_episode_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_story_centroid_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_article_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_topic')
    op.drop_table('article_entity')
    op.drop_index('ix_thread_story_thread_added', table_name='thread_story')
    op.drop_table('thread_story')
    op.drop_index(op.f('ix_prediction_story_id'), table_name='prediction')
    op.drop_index('ix_prediction_predicted_at', table_name='prediction')
    op.drop_index('ix_prediction_confidence', table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_episode_thread_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_story_id'), table_name='episode')
    op.drop_index('ix_episode_published_at', table_name='episode')
    op.drop_index(op.f('ix_episode_podcast_source_id'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_article_url_hash'), table_name='article')
    op.drop_index('ix_article_title_hash_published_at', table_name='article')
    op.drop_index('ix_article_story_id', table_name='article')
    op.drop_index(op.f('ix_article_source_id'), table_name='article')
    op.drop_index('ix_article_published_at', table_name='article')
    op.drop_table('article')
    op.drop_index('ix_anomaly_type_severity', table_name='anomaly')
    op.drop_index('ix_anomaly_detected_at', table_name='anomaly')
    op.drop_table('anomaly')
    op.drop_index('ix_story_velocity_score', table_name='story')
    op.drop_index(op.f('ix_story_thread_id'), table_name='story')
    op.drop_index(op.f('ix_story_slug'), table_name='story')
    op.drop_index('ix_story_primary_country_state', table_name='story')
    op.drop_index('ix_story_last_updated_at', table_name='story')
    op.drop_index('ix_story_first_seen_at', table_name='story')
    op.drop_table('story')
    op.drop_index('ix_ingestion_run_source_started', table_name='ingestion_run')
    op.drop_index(op.f('ix_ingestion_run_source_id'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index('ix_entity_cooccurrence_window_start', table_name='entity_cooccurrence')
    op.drop_table('entity_cooccurrence')
    op.drop_index(op.f('ix_topic_slug'), table_name='topic')
    op.drop_table('topic')
    op.drop_index('ix_thread_status_last_updated', table_name='thread')
    op.drop_index(op.f('ix_thread_slug'), table_name='thread')
    op.drop_table('thread')
    op.drop_index(op.f('ix_source_slug'), table_name='source')
    op.drop_index(op.f('ix_source_region'), table_name='source')
    op.drop_index(op.f('ix_source_is_active'), table_name='source')
    op.drop_index(op.f('ix_source_country'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_podcast_source_slug'), table_name='podcast_source')
    op.drop_index(op.f('ix_podcast_source_is_active'), table_name='podcast_source')
    op.drop_index(op.f('ix_podcast_source_country'), table_name='podcast_source')
    op.drop_table('podcast_source')
    op.drop_table('indian_state')
    op.drop_index(op.f('ix_entity_type'), table_name='entity')
    op.drop_index(op.f('ix_entity_slug'), table_name='entity')
    op.drop_index(op.f('ix_entity_name'), table_name='entity')
    op.drop_table('entity')
    op.drop_table('daily_snapshot')
    op.drop_index(op.f('ix_audio_brief_date'), table_name='audio_brief')
    op.drop_table('audio_brief')
    # ### end Alembic commands ###
